[package]
name = "DNS_honeypot"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
chrono = "0.4.42"
sqlx = { version = "0.8", features = [ "runtime-tokio", "sqlite"] }
hickory-server = "0.25.2"
rand = "0.9.2"