version: "3.8"

services:
  honeypot:
    build: .
    container_name: dns_honeypot
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=/app/data/honeypot.db
      - TZ=Europe/Warsaw
    restart: unless-stopped
    networks:
      - honeynet

  db_viewer:
    image: coleifer/sqlite-web
    container_name: db_viewer
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=honeypot.db
      - SQLITE_WEB_PASSWORD=haslo  # Zmien haslo!!!
    networks:
      - honeynet

networks:
  honeynet:
    driver: bridge